version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Restoring NuGet packages...
      - dotnet restore
  build:
    commands:
      - echo Building the application...
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Publishing the application...
      - dotnet publish --configuration Release --output ./publish
#artifacts:
  #files:
    #- '**/*'
  #base-directory: 'WebbeesitePortal/publish'
